### ISSUE TITLE
Header Bits

### ISSUE THREAD

**Issue by djchapm** [leaty/camctl#4]
Hi, Just curious as I've never written a USB Driver before - how did you figure out which bits were for what, and the possible range of values?  Thanks
def fan(self, speed):
		print('Setting fan speed to {}..'.format(speed))
		self.device.write(1, [2, 77, 0, 0, speed, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

	def pump(self, speed):
		print('Setting pump speed to {}..'.format(speed))
		self.device.write(1, [2, 77, 64, 0, speed, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Comment by leaty** [comment]
Hi, for simple commands it's pretty easy, others not so much. The best thing of course would be if e.g. NZXT made the USB interface available so we need not guess, but that usually doesn't happen with any proprietary stuff. So instead, we need to use something that listens on what is sent/received through the USB port, unfortunately all we can see is raw data so we can't understand any of it.

I'll give you an example for this cooler: since the CAM software is Windows only, we'll use Wireshark's USBPcap to listen on the USB port. Unfortunately all we can see is spam of data every 0.1 seconds, this would be the temp/speed updates, we need to filter these out first.

Once it is completely or nearly completely silent in Wireshark, we can begin testing. So we'll go into CAM software and change the fan speed to say 80, now we'll see a nice entry in Wireshark - we want to look at the Leftover Data field - if we do it again but set it to 60 and then again back to 80. We'll have 3 nice entries where we can easily depict what changed, the ones that changed and remained consistent with the speeds we set (80 showed same twice, 60 differs), is simply the speed, while the rest in this case is "fan" and probably some other header stuff. But all we need to do is to replicate this data and send it to the cooler while being able to change the speed part.

I hope that helps.

EDIT:
It's also worth noting that you can send the data in different formats, what I did here was to take the leftover capture data (e.g. fan: '024d00004600000000000000000000000000000000000000') and convert it using `[int(''.join([data[i], data[i+1]]), base=16) for i in range(0, len(data), 2)]`

```
def conv(data):
	return [int(''.join([data[i], data[i+1]]), base=16) for i in range(0, len(data), 2)]

fan = '024d00004600000000000000000000000000000000000000'
print(conv(fan))
```

Which gives you `[2, 77, 0, 0, 70, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]` where 70 is 70% fan speed.
